# Site settings
remote_theme: LeakyAbstractions/pretty-docs
url: https://leakyabstractions.github.io
title: &site_title FluentValidation
branding:
  highlight: Fluent
  bold: Validation
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true

# Owner
owner:
  name: Jeremy Skinner
  twitter: &site_owner_twitter JeremySkinner
  copyright:
    author: "[Jeremy Skinner](http://jeremyskinner.co.uk/)"

# Google Analytics
google_analytics: UA-884625-14

# Collections
collections:
  doc:
    output: true
    permalink: /:path

# Default values
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
